"use client";

import { Heart, ImagePlus, MessageCircle, Send, SmilePlus, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { useLocale } from "@/components/locale-provider";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";

type FeedPost={id:string;author:string;role:string;body:string;created:string;image?:string;reactions:Record<string,number>;comments:string[];myReaction?:string};
const initialPosts:FeedPost[]=[
 {id:"p1",author:"سارة خالد",role:"مشرفة خدمة العملاء",body:"فخورون بفريق تشات الزبائن بعد تحقيق أعلى تقييم رضا لهذا الشهر 🎉 شكراً لجهودكم والتزامكم.",created:"منذ 35 دقيقة",reactions:{"❤️":18,"👏":12,"🎉":9},comments:["مبروك للجميع!","إنجاز رائع، القادم أجمل."]},
 {id:"p2",author:"أحمد منصور",role:"مدير العمليات",body:"صور من تكريم فريق التوصيل في مكتب طولكرم. نجاحنا يبدأ من الأشخاص الذين يصنعون الفرق كل يوم.",created:"منذ ساعتين",image:"/haat-login-reference.png",reactions:{"❤️":26,"👏":21,"🔥":7},comments:["كل الاحترام للفريق."]}
];

export default function Community(){
 const{locale}=useLocale();const ar=locale==="ar";const[posts,setPosts]=useState(initialPosts);const[body,setBody]=useState("");const[image,setImage]=useState<string>();const[comment,setComment]=useState<Record<string,string>>({});
 useEffect(()=>{if(!isSupabaseConfigured)return;const s=createClient()!;(async()=>{const{data:{user}}=await s.auth.getUser();const{data}=await s.from("company_posts").select("*,author:profiles(full_name),post_reactions(emoji,user_id),post_comments(body)").order("created_at",{ascending:false});if(data?.length)setPosts(data.map((p:any)=>({id:p.id,author:p.author?.full_name||"HAAT",role:"HAAT Team",body:p.body,created:new Date(p.created_at).toLocaleString(locale),image:p.image_url,reactions:(p.post_reactions||[]).reduce((a:Record<string,number>,r:any)=>(a[r.emoji]=(a[r.emoji]||0)+1,a),{}),comments:(p.post_comments||[]).map((c:any)=>c.body),myReaction:(p.post_reactions||[]).find((r:any)=>r.user_id===user?.id)?.emoji})))})()},[locale]);
 const pick=(file?:File)=>{if(file){if(file.size>5_000_000)return toast.error(ar?"حجم الصورة أكبر من 5MB":"Image must be under 5MB");setImage(URL.createObjectURL(file))}};
 const publish=async()=>{if(!body.trim())return toast.error(ar?"اكتب محتوى المنشور أولاً":"Write something first");if(isSupabaseConfigured){const s=createClient()!;const{data:{user}}=await s.auth.getUser();if(user){const{error}=await s.from("company_posts").insert({author_id:user.id,body:body.trim()});if(error)return toast.error(error.message)}}setPosts([{id:`local-${Date.now()}-${Math.random().toString(36).slice(2)}`,author:ar?"محمد أحمد":"Mohammad Ahmad",role:ar?"موظف HAAT":"HAAT Employee",body:body.trim(),created:ar?"الآن":"Now",image,reactions:{},comments:[]},...posts]);setBody("");setImage(undefined);toast.success(ar?"تم نشر المنشور":"Post published")};
 const react=async(id:string,emoji:string)=>{const post=posts.find(p=>p.id===id);if(!post||post.myReaction===emoji)return toast.info(ar?"تفاعلك مسجل بالفعل":"Your reaction is already recorded");setPosts(posts.map(p=>{if(p.id!==id)return p;const next={...p.reactions};if(p.myReaction)next[p.myReaction]=Math.max(0,(next[p.myReaction]||0)-1);next[emoji]=(next[emoji]||0)+1;return{...p,reactions:next,myReaction:emoji}}));if(isSupabaseConfigured){const s=createClient()!;const{data:{user}}=await s.auth.getUser();if(user){const{error}=await s.from("post_reactions").upsert({post_id:id,user_id:user.id,emoji});if(error)toast.error(error.message)}}};
 const addComment=async(id:string)=>{const value=comment[id]?.trim();if(!value)return;setPosts(posts.map(p=>p.id===id?{...p,comments:[...p.comments,value]}:p));setComment({...comment,[id]:""});if(isSupabaseConfigured){const s=createClient()!;const{data:{user}}=await s.auth.getUser();if(user)await s.from("post_comments").insert({post_id:id,author_id:user.id,body:value})}};
 return <AppShell title={ar?"مجتمع الشركة":"Company Feed"}>
  <div className="mx-auto grid max-w-6xl gap-6 xl:grid-cols-[1fr_320px]">
   <section className="space-y-5">
    <article className="card p-5"><div className="flex gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[var(--primary)] font-black text-white">م</span><textarea className="input min-h-24 resize-none" value={body} onChange={e=>setBody(e.target.value)} placeholder={ar?"شارك خبراً، إنجازاً، أو فكرة مع فريق HAAT...":"Share news, an achievement, or an idea with HAAT..."}/></div>{image&&<img src={image} alt="Post preview" className="mt-4 max-h-72 w-full rounded-2xl object-cover"/>}<div className="mt-4 flex items-center justify-between border-t border-[var(--line)] pt-4"><label className="btn btn-secondary cursor-pointer text-xs"><ImagePlus size={17}/>{ar?"إضافة صورة":"Add photo"}<input hidden type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0])}/></label><button onClick={publish} className="btn btn-primary"><Send size={17}/>{ar?"نشر":"Post"}</button></div></article>
    {posts.map(post=><article key={post.id} className="card overflow-hidden"><div className="p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[var(--primary-soft)] font-black text-[var(--primary)]">{post.author[0]}</span><div><b className="block text-sm">{post.author}</b><span className="text-[11px] text-[var(--muted)]">{post.role} · {post.created}</span></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-8">{post.body}</p></div>{post.image&&<img src={post.image} alt="" className="max-h-[470px] w-full object-cover"/>}<div className="p-5"><div className="flex flex-wrap gap-2">{["❤️","👏","🎉","🔥"].map(e=><button key={e} onClick={()=>react(post.id,e)} aria-pressed={post.myReaction===e} className={post.myReaction===e?"rounded-full border border-[var(--primary)] bg-[var(--primary)] px-3 py-1.5 text-xs text-white":"rounded-full border border-[var(--line)] bg-[var(--surface-2)] px-3 py-1.5 text-xs hover:border-[var(--primary)]"}>{e} {post.reactions[e]||0}</button>)}</div><div className="my-4 flex items-center gap-5 border-y border-[var(--line)] py-3 text-xs font-bold text-[var(--muted)]"><span className="flex items-center gap-2"><Heart size={17}/>{Object.values(post.reactions).reduce((a,b)=>a+b,0)} {ar?"تفاعل":"reactions"}</span><span className="flex items-center gap-2"><MessageCircle size={17}/>{post.comments.length} {ar?"تعليق":"comments"}</span></div><div className="space-y-2">{post.comments.map((c,i)=><p key={i} className="rounded-2xl bg-[var(--surface-2)] px-4 py-2.5 text-xs">{c}</p>)}</div><div className="mt-3 flex gap-2"><input className="input" value={comment[post.id]||""} onChange={e=>setComment({...comment,[post.id]:e.target.value})} onKeyDown={e=>e.key==="Enter"&&addComment(post.id)} placeholder={ar?"اكتب تعليقاً...":"Write a comment..."}/><button className="toolbar-btn" onClick={()=>addComment(post.id)}><Send size={17}/></button></div></div></article>)}
   </section>
   <aside className="space-y-4"><article className="card p-5"><h3 className="flex items-center gap-2 font-black"><Trophy className="text-amber-500" size={20}/>{ar?"إنجازات هذا الشهر":"This month’s wins"}</h3><ul className="mt-4 space-y-3 text-xs leading-6 text-[var(--muted)]"><li>🏆 {ar?"96% رضا العملاء":"96% customer satisfaction"}</li><li>🚀 {ar?"أسرع وقت استجابة":"Fastest response time"}</li><li>❤️ {ar?"150 موظفاً في فريق واحد":"150 employees, one team"}</li></ul></article><article className="card p-5"><h3 className="flex items-center gap-2 font-black"><SmilePlus size={19}/>{ar?"مجتمع إيجابي":"A positive community"}</h3><p className="mt-2 text-xs leading-6 text-[var(--muted)]">{ar?"شارك باحترام، احتفل بزملائك، وحافظ على خصوصية معلومات العملاء.":"Post respectfully, celebrate teammates, and protect customer privacy."}</p></article></aside>
  </div>
 </AppShell>
}
