import { NextRequest,NextResponse } from "next/server";
import { getUserPermissions,saveUserPermission,sessionUser } from "@/lib/account-store";
import { demoEmployees,departmentHeadEmails } from "@/lib/demo-data";
export const permissionKeys=["view_announcements","create_requests","view_reports","use_tools","submit_complaints","read_guidelines"] as const;
const bearer=(request:NextRequest)=>request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||null;
async function actor(request:NextRequest){const id=await sessionUser(bearer(request));const profile=demoEmployees.find(item=>item.id===id);if(!profile)throw new Error("UNAUTHORIZED");return profile}
const canManage=(profile:(typeof demoEmployees)[number])=>["manager","admin"].includes(profile.role)||departmentHeadEmails.has(profile.email.toLowerCase());
export async function GET(request:NextRequest){try{const profile=await actor(request);const target=request.nextUrl.searchParams.get("userId")||profile.id;if(target!==profile.id&&!canManage(profile))return NextResponse.json({error:"FORBIDDEN"},{status:403});return NextResponse.json({permissions:await getUserPermissions(target)},{headers:{"Cache-Control":"no-store"}})}catch{return NextResponse.json({error:"UNAUTHORIZED"},{status:401})}}
export async function PUT(request:NextRequest){try{const profile=await actor(request);if(!canManage(profile))return NextResponse.json({error:"FORBIDDEN"},{status:403});const body=await request.json() as {userId?:string;permissionKey?:string;allowed?:boolean};if(!body.userId||!permissionKeys.includes(body.permissionKey as typeof permissionKeys[number])||typeof body.allowed!=="boolean")return NextResponse.json({error:"INVALID_INPUT"},{status:422});if(!demoEmployees.some(item=>item.id===body.userId))return NextResponse.json({error:"UNKNOWN_USER"},{status:404});await saveUserPermission(body.userId,body.permissionKey!,body.allowed);return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"تعذر تحديث الصلاحية"},{status:500})}}
