"use client";

import { BellRing, BriefcaseBusiness, Building2, CalendarDays, Camera, Check, Clock3, Languages, Mail, MapPin, Phone, Save, ShieldCheck, Smartphone, UserRoundCog } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { useLocale } from "@/components/locale-provider";
import { disablePushNotifications, enablePushNotifications } from "@/lib/firebase/client";
import { useProfile } from "@/lib/hooks";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";

export default function Profile(){
 const{locale}=useLocale();const ar=locale==="ar";const profile=useProfile();const[push,setPush]=useState(true);const[avatar,setAvatar]=useState<string>();const[uploading,setUploading]=useState(false);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!profile.avatar_url)return;if(profile.avatar_url.startsWith("http")){setAvatar(profile.avatar_url);return}if(isSupabaseConfigured)createClient()!.storage.from("avatars").createSignedUrl(profile.avatar_url,3600).then(({data})=>setAvatar(data?.signedUrl))},[profile.avatar_url]);
 const uploadAvatar=async(file?:File)=>{if(!file)return;if(!file.type.startsWith("image/"))return toast.error(ar?"اختر ملف صورة":"Choose an image file");if(file.size>3_000_000)return toast.error(ar?"حجم الصورة يجب أن يكون أقل من 3MB":"Image must be under 3MB");const preview=URL.createObjectURL(file);setAvatar(preview);if(!isSupabaseConfigured)return toast.success(ar?"تمت معاينة الصورة في الوضع التجريبي":"Photo preview updated in demo mode");setUploading(true);try{const s=createClient()!;const{data:{user}}=await s.auth.getUser();if(!user)throw new Error(ar?"سجّل الدخول أولاً":"Sign in first");const ext=file.name.split(".").pop()||"jpg";const path=`${user.id}/avatar-${Date.now()}.${ext}`;const{error}=await s.storage.from("avatars").upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;const{error:updateError}=await s.from("profiles").update({avatar_url:path}).eq("id",user.id);if(updateError)throw updateError;const{data}=await s.storage.from("avatars").createSignedUrl(path,3600);setAvatar(data?.signedUrl||preview);toast.success(ar?"تم حفظ الصورة الشخصية":"Profile photo saved")}catch(error){toast.error(error instanceof Error?error.message:"Upload failed")}finally{setUploading(false)}};
 const togglePush=async()=>{try{push?await disablePushNotifications():await enablePushNotifications();setPush(!push);toast.success(push?(ar?"تم تعطيل إشعارات هذا الجهاز":"Device notifications disabled"):(ar?"تم تفعيل إشعارات هذا الجهاز":"Device notifications enabled"))}catch(error){toast.error(error instanceof Error?error.message:"Unable to update notifications")}};
 const info=[
  {label:ar?"الرقم الوظيفي":"Employee ID",value:profile.employee_id,icon:UserRoundCog},{label:ar?"البريد الرسمي":"Company email",value:profile.email,icon:Mail},{label:ar?"رقم الهاتف":"Phone number",value:"+970 59 *** **45",icon:Phone},{label:ar?"القسم":"Department",value:profile.department?.name||"Customer Chat",icon:Building2},{label:"Job Title",value:"Senior Agent",icon:BriefcaseBusiness},{label:ar?"تاريخ الانضمام":"Join date",value:ar?"12 مارس 2023":"12 March 2023",icon:CalendarDays},{label:ar?"المشرف المباشر":"Direct supervisor",value:ar?"سارة خالد":"Sara Khaled",icon:UserRoundCog},{label:ar?"نوع الدوام":"Employment type",value:"Full Time · Rotating Shift",icon:Clock3},{label:ar?"الموقع":"Location",value:"Tulkarm Office",icon:MapPin},{label:ar?"اللغة المفضلة":"Preferred language",value:ar?"العربية":"English",icon:Languages}
 ];
 const permissions=ar?["قراءة التعميمات","مشاهدة الأداء","مشاهدة المراجعات","تأكيد الاطلاع","إرسال الرسائل والتعليقات"]:["Read announcements","View performance","View reviews","Acknowledge updates","Send messages and comments"];
 return <AppShell title={ar?"ملف الموظف":"Employee Profile"}>
  <section className="mb-6 overflow-hidden rounded-3xl bg-gradient-to-l from-[#ff6b82] to-[#ed294d] p-6 text-white shadow-xl shadow-rose-200/40 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="relative grid size-28 place-items-center overflow-visible rounded-full border-4 border-white/60 bg-white/20 text-3xl font-black">{avatar?<img src={avatar} alt="Profile" className="size-full rounded-full object-cover"/>:profile.full_name[0]}<input ref={input} hidden type="file" accept="image/*" onChange={e=>uploadAvatar(e.target.files?.[0])}/><button disabled={uploading} onClick={()=>input.current?.click()} className="absolute bottom-0 left-0 grid size-9 place-items-center rounded-full bg-white text-[var(--primary)] shadow-lg" aria-label={ar?"تغيير الصورة الشخصية":"Change profile photo"}><Camera size={17}/></button></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-black">{profile.full_name}</h2><span className="badge border-white/40 bg-white/20 text-white">Active</span></div><p className="mt-2 text-sm text-white/90">Senior Agent · {profile.department?.name||"Customer Chat"}</p><p className="mt-2 text-xs text-white/75">{ar?"اضغط على أيقونة الكاميرا لإضافة أو تغيير الصورة":"Use the camera button to add or change your photo"}</p></div></div></section>
  <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><section className="space-y-6"><article className="card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-black">{ar?"بيانات الموظف":"Employee details"}</h3><p className="text-xs text-[var(--muted)]">{ar?"المعلومات الأساسية والوظيفية":"Personal and employment information"}</p></div><button onClick={()=>toast.success(ar?"تم حفظ البيانات":"Details saved")} className="btn btn-primary"><Save size={16}/>{ar?"حفظ":"Save"}</button></div><div className="grid gap-3 sm:grid-cols-2">{info.map(({label,value,icon:Icon})=><div className="flex items-center gap-3 rounded-2xl border border-[var(--line)] p-4" key={label}><i className="row-icon !size-10"><Icon size={17}/></i><div className="min-w-0"><p className="text-[11px] text-[var(--muted)]">{label}</p><b className="block truncate text-sm">{value}</b></div></div>)}</div></article></section>
   <aside className="space-y-6"><article className="card p-5"><h3 className="flex items-center gap-2 font-black"><ShieldCheck size={19}/>{ar?"الصلاحيات":"Permissions"}</h3><div className="mt-4 space-y-3">{permissions.map(item=><div className="flex items-center gap-2 text-sm" key={item}><i className="grid size-6 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check size={14}/></i>{item}</div>)}</div></article><article className="card p-5"><h3 className="mb-5 font-black">{ar?"التحقق والأمان":"Verification & security"}</h3><div className="space-y-3 text-sm"><div className="flex items-center justify-between"><span>{ar?"البريد الرسمي":"Company email"}</span><span className="badge read">Verified</span></div><div className="flex items-center justify-between"><span>Google</span><span className="badge">{ar?"متاح":"Available"}</span></div></div></article><article className="card p-5"><h3 className="mb-5 font-black">{ar?"إشعارات الجهاز":"Device notifications"}</h3><div className="flex items-center gap-3"><i className="row-icon !size-11"><BellRing size={19}/></i><div className="flex-1"><b className="text-sm">Push Notifications</b><p className="text-xs text-[var(--muted)]">{ar?"تعميم جديد ورسالة جديدة":"New announcements and messages"}</p></div><button onClick={togglePush} className={`relative h-7 w-12 rounded-full ${push?"bg-[var(--primary)]":"bg-slate-300"}`}><i className={`absolute top-1 size-5 rounded-full bg-white transition-all ${push?"left-1":"left-6"}`}/></button></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-[var(--surface-2)] p-3 text-xs text-[var(--muted)]"><Smartphone size={16}/>{push?(ar?"هذا الجهاز يستقبل الإشعارات":"This device receives notifications"):(ar?"الإشعارات معطلة":"Notifications are disabled")}</div></article></aside>
  </div>
 </AppShell>
}
