"use client";
import Link from "next/link";
import { Bookmark, CheckCircle2, FileText, Paperclip, Pin, UserRound } from "lucide-react";
import type { Announcement } from "@/lib/types";
import { cn, priorityLabel, relativeTime } from "@/lib/utils";
export function AnnouncementCard({item,compact=false}:{item:Announcement,compact?:boolean}){const tones={urgent:"bg-red-50 text-red-700 dark:bg-red-950/40",important:"bg-orange-50 text-orange-700 dark:bg-orange-950/40",normal:"bg-slate-100 text-slate-600 dark:bg-slate-800"};return <article className={cn("card group relative overflow-hidden p-5 hover:-translate-y-0.5 hover:border-[color-mix(in_srgb,var(--primary)_35%,var(--line))]",!item.is_read&&"border-r-4 border-r-[var(--primary)]")}>
  <div className="flex items-start gap-4"><div className="min-w-0 flex-1"><div className="mb-3 flex flex-wrap items-center gap-2"><span className={cn("rounded-full px-2.5 py-1 text-[11px] font-bold",tones[item.priority])}>{priorityLabel[item.priority]}</span>{item.is_pinned&&<span className="flex items-center gap-1 text-[11px] font-bold text-[var(--primary)]"><Pin size={13}/>مثبت</span>}{!item.is_read&&<span className="rounded-full bg-[var(--primary-soft)] px-2 py-1 text-[10px] font-bold text-[var(--primary)]">جديد</span>}</div><h3 className="text-[15px] font-extrabold leading-7 sm:text-base">{item.title}</h3>{!compact&&<p className="mt-2 line-clamp-2 text-sm leading-7 text-[var(--muted)]">{item.body}</p>}<div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-[11px] text-[var(--muted)]"><span className="flex items-center gap-1"><UserRound size={14}/>{item.author?.full_name}</span><span>{relativeTime(item.published_at)}</span><span>{item.target_label}</span>{item.attachments?.length?<span className="flex items-center gap-1"><Paperclip size={14}/>{item.attachments.length} مرفق</span>:null}</div></div><button aria-label="حفظ" className="text-[var(--muted)] hover:text-[var(--primary)]"><Bookmark size={19} className={item.is_bookmarked?"fill-current text-[var(--primary)]":""}/></button></div>
  <div className="mt-5 flex items-center justify-between border-t border-[var(--line)] pt-4"><span className={cn("flex items-center gap-1 text-xs font-bold",item.is_read?"text-emerald-600":"text-[var(--muted)]")}>{item.is_read?<><CheckCircle2 size={15}/>تمت القراءة</>:<><FileText size={15}/>بانتظار القراءة</>}</span><Link href={`/announcements/${item.id}`} className="text-xs font-extrabold text-[var(--primary)] hover:underline">فتح التعميم ←</Link></div>
  </article>}
