export type CommunityPerson={id:string;name:string;title:string;department:string;employeeId:string;email:string;phone:string;location:string;joined:string;skills:string[];role:"employee"|"supervisor"|"manager"|"admin"};
export const communityPeople:CommunityPerson[]=[
 {id:"mohammad-ahmad",name:"محمد أحمد",title:"موظف خدمة زبائن",department:"تشات الزبائن",employeeId:"1001",email:"mohammad.ahmad@haat.ps",phone:"داخلي 201",location:"رام الله",joined:"2024",skills:["خدمة الزبائن","حل المشكلات","التواصل"],role:"employee"},
 {id:"sara-khaled",name:"سارة خالد",title:"مشرفة خدمة الزبائن",department:"تشات الزبائن",employeeId:"1012",email:"sara.khaled@haat.ps",phone:"داخلي 214",location:"رام الله",joined:"2022",skills:["إدارة الفرق","التدريب","الجودة"],role:"supervisor"},
 {id:"ahmad-mansour",name:"أحمد منصور",title:"مدير العمليات",department:"الإدارة",employeeId:"1003",email:"ahmad.mansour@haat.ps",phone:"داخلي 101",location:"رام الله",joined:"2020",skills:["العمليات","القيادة","التخطيط"],role:"manager"},
 {id:"mahmoud-nassar",name:"محمود نصّار",title:"موظف تشات",department:"تشات الزبائن",employeeId:"1034",email:"mahmoud.nassar@haat.ps",phone:"داخلي 233",location:"نابلس",joined:"2024",skills:["Chat","CRM","التوثيق"],role:"employee"},
 {id:"reem-shahrour",name:"ريم شحرور",title:"قائدة فريق",department:"فويس سنتر",employeeId:"1021",email:"reem.shahrour@haat.ps",phone:"داخلي 218",location:"الخليل",joined:"2022",skills:["إدارة الفريق","Voice","التدريب"],role:"supervisor"},
 {id:"layan-awda",name:"ليان عودة",title:"موظفة فويس سنتر",department:"فويس سنتر",employeeId:"1048",email:"layan.awda@haat.ps",phone:"داخلي 249",location:"رام الله",joined:"2025",skills:["Voice","الاستماع","المتابعة"],role:"employee"},
 {id:"noor-jarrar",name:"نور جرار",title:"موظفة كنترول",department:"كنترول المرسلين",employeeId:"1028",email:"noor.jarrar@haat.ps",phone:"داخلي 225",location:"طولكرم",joined:"2023",skills:["Control","التنسيق","المتابعة"],role:"employee"},
];
export const mentionTargets=[...communityPeople.map(p=>({id:p.id,label:p.name,kind:"employee" as const,subtitle:p.department})),{id:"management",label:"الإدارة",kind:"group" as const,subtitle:"جميع أعضاء الإدارة"},{id:"all-employees",label:"جميع الموظفين",kind:"group" as const,subtitle:"كل موظفي HAAT"},{id:"dep-chat",label:"قسم تشات الزبائن",kind:"department" as const,subtitle:"قسم"},{id:"dep-control",label:"قسم كنترول المرسلين",kind:"department" as const,subtitle:"قسم"},{id:"dep-voice",label:"قسم فويس سنتر",kind:"department" as const,subtitle:"قسم"}];
export const personByName=(name:string)=>communityPeople.find(p=>p.name===name);
