"use client";
import{useEffect,useState}from"react";
import{createClient,isSupabaseConfigured}from"./supabase/client";
import{demoAnnouncements,demoEmployees,demoNotifications,demoProfile,departments as demoDepartments}from"./demo-data";
import type{Announcement,Department,NotificationItem,Profile}from"./types";
export function useAnnouncements(){const[data,setData]=useState<Announcement[]>(isSupabaseConfigured?[]:demoAnnouncements);const[loading,setLoading]=useState(isSupabaseConfigured);useEffect(()=>{if(!isSupabaseConfigured)return;const s=createClient()!;(async()=>{const{data:{user}}=await s.auth.getUser();const[{data:rows},{data:reads},{data:marks}]=await Promise.all([s.from("announcements").select("*,author:profiles!author_id(full_name,avatar_url),attachments(*)").eq("status","published").order("is_pinned",{ascending:false}).order("published_at",{ascending:false}),user?s.from("announcement_reads").select("announcement_id,read_at").eq("user_id",user.id):Promise.resolve({data:[]}),user?s.from("announcement_bookmarks").select("announcement_id").eq("user_id",user.id):Promise.resolve({data:[]})]);const readMap=new Map((reads||[]).map(r=>[r.announcement_id,r.read_at]));const markSet=new Set((marks||[]).map(r=>r.announcement_id));setData((rows||[]).map((a:any)=>({...a,target_label:"موجّه إليك",read_count:a.read_count||0,recipient_count:a.recipient_count||0,is_read:readMap.has(a.id),read_at:readMap.get(a.id),is_bookmarked:markSet.has(a.id)})));setLoading(false)})()},[]);return{data,loading,setData}}
export function useDepartments(){const[data,setData]=useState<Department[]>(isSupabaseConfigured?[]:demoDepartments);useEffect(()=>{if(isSupabaseConfigured)createClient()!.from("departments").select("*").eq("is_active",true).order("name").then(({data})=>setData(data||[]))},[]);return data}
export function useEmployees(){const[data,setData]=useState<Profile[]>(isSupabaseConfigured?[]:demoEmployees);useEffect(()=>{if(isSupabaseConfigured)createClient()!.from("profiles").select("*,department:departments(*)").order("full_name").then(({data})=>setData((data||[]) as Profile[]))},[]);return data}
export function useNotifications(){const[data,setData]=useState<NotificationItem[]>(isSupabaseConfigured?[]:demoNotifications);useEffect(()=>{if(isSupabaseConfigured)createClient()!.from("notifications").select("*").order("created_at",{ascending:false}).then(({data})=>setData((data||[]) as NotificationItem[]))},[]);return{data,setData}}
export function useProfile(){const[data,setData]=useState<Profile>(demoProfile);useEffect(()=>{if(isSupabaseConfigured){const s=createClient()!;s.auth.getUser().then(({data:{user}})=>{if(user)s.from("profiles").select("*,department:departments(*)").eq("id",user.id).single().then(({data})=>{if(data)setData(data as Profile)})})}else{const id=window.localStorage.getItem("haat-current-user");const profile=demoEmployees.find(item=>item.id===id);if(profile)setData(profile)}},[]);return data}
