export type KnowledgeCategory = "policy"|"procedure"|"reply"|"compensation"|"announcement"|"instruction"|"case"|"faq"|"training";
export type KnowledgeArticle = {
  id:string; title:string; summary:string; content:string; category:KnowledgeCategory; department:string;
  keywords:string[]; language:"ar"|"en"|"he"|"multi"; status:"active"|"archived"; version:number;
  updatedBy:string; updatedAt:string; sourceLabel:string;
};

const stamp = "2026-09-02T08:00:00.000Z";
export const defaultKnowledge:KnowledgeArticle[] = [
  {id:"kb-late-order",title:"إجراء الطلب المتأخر",summary:"خطوات التعامل مع الطلب المتأخر حسب موقع المرسل وحالة تجهيز المطعم.",content:"تحقق من وقت الطلب وموقع المرسل وحالة تجهيز المطعم. إذا كان المرسل عند المطعم والطلب غير جاهز، تواصل مع المطعم لتثبيت وقت تجهيز واضح، أبلغ الزبون بالمدة الواقعية، وثّق الحالة على الطلب. إذا تجاوز التأخير الحد المعتمد أو تعذر إعطاء وقت واضح، صعّد الحالة للمشرف قبل تقديم أي تعويض أو إلغاء.",category:"procedure",department:"Customer Chat",keywords:["متأخر","تأخير","المطعم ما برد","مش جاهز","المرسل عند المطعم","late order","delay"],language:"multi",status:"active",version:1,updatedBy:"HAAT Operations",updatedAt:stamp,sourceLabel:"سياسة العمليات · الطلبات المتأخرة"},
  {id:"kb-compensation",title:"ضوابط التعويض",summary:"لا يُمنح التعويض إلا وفق سبب موثّق وحدود السياسة أو موافقة المشرف.",content:"قبل اقتراح أي تعويض، وثّق الخطأ والجهة المسؤولة وتحقق من أن الحالة مؤهلة حسب جدول التعويضات المعتمد. لا تعد الزبون بقيمة أو Coupon غير مذكور في السياسة. عند غياب بند واضح أو وجود شك، حوّل الحالة للمشرف.",category:"compensation",department:"All",keywords:["تعويض","كوبون","coupon","refund","بارد","ناقص","سعر غلط"],language:"multi",status:"active",version:1,updatedBy:"Quality Team",updatedAt:stamp,sourceLabel:"سياسة التعويضات المعتمدة"},
  {id:"kb-no-answer",title:"المطعم لا يجيب",summary:"محاولات التواصل والتوثيق ثم التصعيد عند غياب رد مؤكد.",content:"حاول التواصل عبر القناة المعتمدة، تحقق من بيانات المطعم وحالة الطلب، وسجّل وقت المحاولة. لا تعطِ الزبون وقت تجهيز غير مؤكد. بعد استنفاد المحاولات المعتمدة، صعّد الحالة للمشرف أو الكنترول مع رقم الطلب والتفاصيل.",category:"procedure",department:"Customer Chat",keywords:["المطعم ما برد","لا يجيب","no answer","restaurant","اتصال"],language:"multi",status:"active",version:1,updatedBy:"HAAT Operations",updatedAt:stamp,sourceLabel:"إجراء التواصل مع المطاعم"},
  {id:"kb-missing-item",title:"طلب ناقص أو صنف مفقود",summary:"توثيق الصنف والتحقق من الطلب ثم تطبيق الحل أو التصعيد.",content:"راجع تفاصيل الطلب مع الزبون، حدّد الصنف المفقود بدقة، راجع فاتورة الطلب والتعديلات، ووثّق النتيجة. طبّق التعويض فقط إذا انطبقت السياسة بوضوح؛ وإلا صعّد للمشرف.",category:"procedure",department:"Customer Chat",keywords:["ناقص","مفقود","missing item","صنف","طلب ناقص"],language:"multi",status:"active",version:1,updatedBy:"Quality Team",updatedAt:stamp,sourceLabel:"إجراء الطلب الناقص"},
  {id:"kb-documentation",title:"توثيق الحالات",summary:"كل إجراء وتحويل يحتاج Internal Note واضحة وقابلة للتتبع.",content:"اكتب رقم الطلب، ملخص المشكلة، ما تم التحقق منه، الجهات التي تم التواصل معها، النتيجة، وسبب التصعيد أو التعويض. لا تترك الطلب دون تعليق، ولا تستخدم ملاحظة مبهمة.",category:"policy",department:"All",keywords:["تعليق","كومنت","توثيق","internal note","documentation","ملاحظة"],language:"multi",status:"active",version:1,updatedBy:"QA Team",updatedAt:stamp,sourceLabel:"معيار QA · Documentation"},
  {id:"kb-closing",title:"الخاتمة وفحص الرضا",summary:"إنهاء المحادثة بعد تأكيد الحل وسؤال الزبون إن كان يحتاج خدمة أخرى.",content:"قبل الإغلاق، لخّص ما تم، تأكد أن الزبون فهم الإجراء، اسأله إن كان يحتاج خدمة أخرى، ثم استخدم خاتمة مهنية. تجنب وضع الزبون على الانتظار مباشرة بعد الرد دون توضيح.",category:"training",department:"Customer Chat",keywords:["خاتمة","خدمة ثانية","إغلاق","closing","satisfaction","انتظار"],language:"multi",status:"active",version:1,updatedBy:"QA Team",updatedAt:stamp,sourceLabel:"معيار QA · Satisfaction Check & Proper Closing"},
  {id:"kb-payment",title:"مشكلة دفع",summary:"التحقق من حالة العملية وعدم طلب بيانات بطاقة حساسة.",content:"تحقق من حالة الدفع في النظام ورقم الطلب والمبلغ. لا تطلب رقم البطاقة الكامل أو رمز التحقق. إذا كانت العملية معلقة أو غير متطابقة، صعّد لفريق المدفوعات مع التوثيق.",category:"policy",department:"Customer Chat",keywords:["دفع","بطاقة","payment","خصم","مبلغ"],language:"multi",status:"active",version:1,updatedBy:"HAAT Operations",updatedAt:stamp,sourceLabel:"سياسة أمن المدفوعات"},
  {id:"kb-cancel",title:"طلب الإلغاء",summary:"لا يتم تأكيد الإلغاء قبل التحقق من مرحلة الطلب والسياسة.",content:"تحقق من مرحلة الطلب ومن بدأ التجهيز وموقع المرسل. اشرح للزبون الخيارات المتاحة حسب الحالة. إذا لم يكن الإلغاء واضح الصلاحية أو ترتبت كلفة، صعّد للمشرف قبل تأكيد الإلغاء أو التعويض.",category:"procedure",department:"Customer Chat",keywords:["إلغاء","الغاء","cancel","ما بدي الطلب"],language:"multi",status:"active",version:1,updatedBy:"HAAT Operations",updatedAt:stamp,sourceLabel:"إجراء إلغاء الطلب"},
];

const normalize=(value:string)=>value.toLowerCase().replace(/[ًٌٍَُِّْـ]/g,"").replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/[^\p{L}\p{N}\s]/gu," ");
export function searchKnowledge(query:string,articles:KnowledgeArticle[]=defaultKnowledge){
  const words=normalize(query).split(/\s+/).filter(word=>word.length>1);
  return articles.filter(a=>a.status==="active").map(article=>{
    const hay=normalize([article.title,article.summary,article.content,...article.keywords].join(" "));
    const hits=words.filter(word=>hay.includes(word));
    const keywordBonus=article.keywords.some(keyword=>normalize(query).includes(normalize(keyword)))?5:0;
    return {article,score:hits.length+keywordBonus,hits};
  }).filter(result=>result.score>0).sort((a,b)=>b.score-a.score);
}

export type AssistResult={found:boolean;problemType:string;summary:string;procedure:string[];policy:string;escalation:boolean;compensation:"eligible"|"not_eligible"|"requires_approval";replies:{ar:string;he:string;en:string};internalNote:string;sources:KnowledgeArticle[]};
export function resolveCase(input:string,articles:KnowledgeArticle[]=defaultKnowledge):AssistResult{
  const matches=searchKnowledge(input,articles);const source=matches[0];
  if(!source||source.score<2)return{found:false,problemType:"حالة غير مصنفة",summary:input,procedure:[],policy:"لم يتم العثور على إجراء معتمد لهذه الحالة، يرجى مراجعة المشرف.",escalation:true,compensation:"requires_approval",replies:{ar:"سأراجع الحالة مع المشرف للتأكد من الإجراء الصحيح قبل إعطائك أي معلومة.",he:"אבדוק את המקרה מול האחראי כדי לוודא את הנוהל הנכון.",en:"I’ll check this case with the supervisor to confirm the correct procedure."},internalNote:`حالة غير موثقة: ${input} — تم التحويل للمشرف.`,sources:[]};
  const problemType=source.article.title;const hasComp=matches.some(m=>m.article.category==="compensation");const escalation=/غير|تعذر|مش واضح|55|60|90|ساعه|ساعة|الغاء|إلغاء/.test(normalize(input));
  return{found:true,problemType,summary:input,procedure:["تحقق من رقم الطلب والوقت والحالة الحالية.",source.article.content,"وثّق كل خطوة والنتيجة في Internal Note.",...(escalation?["صعّد الحالة للمشرف قبل أي وعد نهائي."]:[])],policy:source.article.summary,escalation,compensation:hasComp?"requires_approval":"not_eligible",replies:{ar:"أفهم انزعاجك وأعتذر عن التأخير. تحققت من الحالة وسأتابع الآن مع الجهة المعنية وأعطيك تحديثًا واضحًا دون وعود غير مؤكدة.",he:"אני מבין את אי הנוחות ומתנצל על העיכוב. בדקתי את המקרה ואעדכן אותך במידע מאומת.",en:"I understand the frustration and I’m sorry for the delay. I’ve checked the case and will provide a verified update without making an uncertain promise."},internalNote:`الحالة: ${input}\nالتحقق: تمت مراجعة حالة الطلب والجهة المعنية.\nالإجراء: ${source.article.title}${escalation?" — تم التصعيد للمشرف":""}.`,sources:matches.slice(0,3).map(m=>m.article)};
}
