import { defaultKnowledge, type KnowledgeArticle } from "@/lib/knowledge";

type KnowledgeRow={id:string;title:string;summary:string;content:string;category:KnowledgeArticle["category"];department:string;keywords:string;language:KnowledgeArticle["language"];status:KnowledgeArticle["status"];version:number;updated_by:string;updated_at:string;source_label:string};
const db=()=>{const runtime=(globalThis as typeof globalThis&{__HAAT_WORKER_ENV__?:{DB?:D1Database}}).__HAAT_WORKER_ENV__;if(!runtime?.DB)throw new Error("KNOWLEDGE_DB_UNAVAILABLE");return runtime.DB};
const map=(row:KnowledgeRow):KnowledgeArticle=>({id:row.id,title:row.title,summary:row.summary,content:row.content,category:row.category,department:row.department,keywords:JSON.parse(row.keywords||"[]"),language:row.language,status:row.status,version:row.version,updatedBy:row.updated_by,updatedAt:row.updated_at,sourceLabel:row.source_label});

export async function ensureKnowledgeStore(){const database=db();await database.batch([
 database.prepare(`CREATE TABLE IF NOT EXISTS knowledge_articles (id TEXT PRIMARY KEY,title TEXT NOT NULL,summary TEXT NOT NULL,content TEXT NOT NULL,category TEXT NOT NULL,department TEXT NOT NULL,keywords TEXT NOT NULL,language TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',version INTEGER NOT NULL DEFAULT 1,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL,source_label TEXT NOT NULL)`),
 database.prepare("CREATE INDEX IF NOT EXISTS idx_knowledge_status_category ON knowledge_articles (status, category)"),
 database.prepare("CREATE INDEX IF NOT EXISTS idx_knowledge_department ON knowledge_articles (department, status)"),
 database.prepare(`CREATE TABLE IF NOT EXISTS simulator_results (id TEXT PRIMARY KEY,user_key TEXT NOT NULL,employee_name TEXT NOT NULL,level TEXT NOT NULL,scenario_title TEXT NOT NULL,overall_score INTEGER NOT NULL,scores_json TEXT NOT NULL,feedback_json TEXT NOT NULL,created_at TEXT NOT NULL)`),
 database.prepare("CREATE INDEX IF NOT EXISTS idx_simulator_user_date ON simulator_results (user_key, created_at)"),
]);
 await database.batch(defaultKnowledge.map(a=>database.prepare(`INSERT OR IGNORE INTO knowledge_articles (id,title,summary,content,category,department,keywords,language,status,version,updated_by,updated_at,source_label) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(a.id,a.title,a.summary,a.content,a.category,a.department,JSON.stringify(a.keywords),a.language,a.status,a.version,a.updatedBy,a.updatedAt,a.sourceLabel)));
}
export async function listKnowledge(includeArchived=false){await ensureKnowledgeStore();const result=await db().prepare(`SELECT * FROM knowledge_articles${includeArchived?"":" WHERE status='active'"} ORDER BY updated_at DESC,title`).all<KnowledgeRow>();return(result.results||[]).map(map)}
export async function saveKnowledge(input:KnowledgeArticle){await ensureKnowledgeStore();const existing=await db().prepare("SELECT version FROM knowledge_articles WHERE id=?").bind(input.id).first<{version:number}>();const version=(existing?.version||0)+1;await db().prepare(`INSERT INTO knowledge_articles (id,title,summary,content,category,department,keywords,language,status,version,updated_by,updated_at,source_label) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,summary=excluded.summary,content=excluded.content,category=excluded.category,department=excluded.department,keywords=excluded.keywords,language=excluded.language,status=excluded.status,version=excluded.version,updated_by=excluded.updated_by,updated_at=excluded.updated_at,source_label=excluded.source_label`).bind(input.id,input.title,input.summary,input.content,input.category,input.department,JSON.stringify(input.keywords),input.language,input.status,version,input.updatedBy,new Date().toISOString(),input.sourceLabel).run()}
export async function deleteKnowledge(id:string){await ensureKnowledgeStore();await db().prepare("UPDATE knowledge_articles SET status='archived',updated_at=? WHERE id=?").bind(new Date().toISOString(),id).run()}
export async function saveSimulatorResult(input:{userKey:string;employeeName:string;level:string;scenarioTitle:string;overallScore:number;scores:Record<string,number>;feedback:unknown}){await ensureKnowledgeStore();await db().prepare("INSERT INTO simulator_results (id,user_key,employee_name,level,scenario_title,overall_score,scores_json,feedback_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),input.userKey,input.employeeName,input.level,input.scenarioTitle,input.overallScore,JSON.stringify(input.scores),JSON.stringify(input.feedback),new Date().toISOString()).run()}
export async function listSimulatorResults(userKey?:string){await ensureKnowledgeStore();const query=userKey?db().prepare("SELECT * FROM simulator_results WHERE user_key=? ORDER BY created_at DESC").bind(userKey):db().prepare("SELECT * FROM simulator_results ORDER BY created_at DESC");return(await query.all()).results||[]}
