"use client";
import { Archive,Headphones,MapPinned,RadioTower,Truck,UsersRound } from "lucide-react";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import type { ShiftLead } from "@/lib/shift-lead-store";
const headers=()=>({Authorization:`Bearer ${window.localStorage.getItem("haat-session-token")||""}`});
const Contact=({icon:Icon,label,name,phone}:{icon:typeof Headphones;label:string;name:string;phone:string})=><div className="rounded-2xl border border-[var(--line)] p-4"><div className="flex items-center gap-2 text-[11px] font-black text-[var(--primary)]"><Icon size={16}/>{label}</div><b className="mt-2 block text-sm">{name}</b>{phone?<a dir="ltr" className="mt-1 block text-left font-mono text-xs font-bold text-[var(--primary)]" href={`tel:${phone}`}>{phone}</a>:<span className="mt-1 block text-xs text-[var(--muted)]">لا يوجد رقم مضاف</span>}</div>;
export default function ShiftLeadsPage(){const[items,setItems]=useState<ShiftLead[]>([]);useEffect(()=>{fetch("/api/shift-leads",{headers:headers()}).then(async(response)=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setItems(data.shifts||[])}).catch(()=>toast.error("تعذر تحميل مسؤولي الشفت"))},[]);const current=items.filter((item)=>item.isCurrent),archive=items.filter((item)=>!item.isCurrent);return <AppShell title="مسؤولو الشفت الحالي"><div className="mx-auto max-w-7xl space-y-6"><section className="page-intro"><div className="page-intro-copy"><i><UsersRound size={25}/></i><div><span>جهات الاتصال التشغيلية</span><h2>مسؤولو الشفت الحالي</h2><p>المسؤولون المتاحون الآن لكل منطقة، مع أرقام الفويس للاتصال المباشر.</p></div></div></section>{current.length?<div className="grid gap-5 xl:grid-cols-2">{current.map((item)=><article key={item.id} className="card overflow-hidden"><header className="flex flex-wrap items-center gap-3 border-b border-[var(--line)] bg-[var(--surface-2)] p-5"><i className="row-icon"><MapPinned size={18}/></i><div className="flex-1"><h3 className="font-black">{item.area}</h3><p className="text-[11px] text-[var(--muted)]">{item.shiftName} · {new Date(item.startsAt).toLocaleString("ar-PS")}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black text-emerald-700">الشفت الحالي</span></header><div className="grid gap-3 p-5 md:grid-cols-3"><Contact icon={Headphones} label="مسؤول خدمة الزبائن" name={item.customerServiceName} phone={item.customerServicePhone}/><Contact icon={Truck} label="مسؤول المرسلين" name={item.courierSupportName} phone={item.courierSupportPhone}/><Contact icon={RadioTower} label="مسؤول التوزيع" name={item.dispatchName} phone={item.dispatchPhone}/></div></article>)}</div>:<div className="card p-10 text-center text-sm text-[var(--muted)]">لم تتم إضافة مسؤولي الشفت الحالي بعد.</div>}<section><h3 className="mb-4 flex items-center gap-2 font-black"><Archive size={19}/>الشفتات السابقة</h3>{archive.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{archive.map((item)=><article key={item.id} className="card p-4 opacity-80"><div className="flex items-center justify-between gap-3"><b>{item.area}</b><span className="badge">{item.shiftName}</span></div><p className="mt-2 text-[10px] text-[var(--muted)]">{new Date(item.startsAt).toLocaleString("ar-PS")}</p><div className="mt-3 space-y-1 text-xs"><p>خدمة الزبائن: {item.customerServiceName}</p><p>المرسلون: {item.courierSupportName}</p><p>التوزيع: {item.dispatchName}</p></div></article>)}</div>:<p className="card p-6 text-sm text-[var(--muted)]">لا يوجد أرشيف شفتات حتى الآن.</p>}</section></div></AppShell>}
