import { NextRequest,NextResponse } from "next/server";
import { sessionUser } from "@/lib/account-store";
import { demoEmployees,departmentHeadEmails } from "@/lib/demo-data";
import { createShiftLead,listShiftLeads } from "@/lib/shift-lead-store";
const bearer=(request:NextRequest)=>request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||null;
const clean=(value:unknown,max:number)=>String(value||"").trim().slice(0,max);
async function actor(request:NextRequest){const id=await sessionUser(bearer(request));const profile=demoEmployees.find((item)=>item.id===id);if(!profile)throw new Error("UNAUTHORIZED");return profile}
export async function GET(request:NextRequest){try{await actor(request);return NextResponse.json({shifts:await listShiftLeads()},{headers:{"Cache-Control":"no-store"}})}catch{return NextResponse.json({error:"UNAUTHORIZED"},{status:401})}}
export async function POST(request:NextRequest){try{const profile=await actor(request);if(!["manager","admin"].includes(profile.role)&&!departmentHeadEmails.has(profile.email.toLowerCase()))return NextResponse.json({error:"FORBIDDEN"},{status:403});const body=await request.json() as Record<string,unknown>;const input={area:clean(body.area,120),shiftName:clean(body.shiftName,80),startsAt:clean(body.startsAt,40),customerServiceName:clean(body.customerServiceName,160),customerServicePhone:clean(body.customerServicePhone,60),courierSupportName:clean(body.courierSupportName,160),courierSupportPhone:clean(body.courierSupportPhone,60),dispatchName:clean(body.dispatchName,160),dispatchPhone:clean(body.dispatchPhone,60),createdBy:profile.full_name};if(!input.area||!input.shiftName||!input.startsAt||!input.customerServiceName||!input.courierSupportName||!input.dispatchName)return NextResponse.json({error:"أكمل المنطقة والشفت وأسماء المسؤولين"},{status:422});return NextResponse.json({shift:await createShiftLead(input)},{status:201})}catch{return NextResponse.json({error:"تعذر حفظ مسؤولي الشفت"},{status:500})}}
