"use client";
import { Bell, Building2, CalendarDays, CalendarHeart, CheckCircle2, FileText, Paperclip, Pin, Search, ShieldCheck, TriangleAlert, Trophy } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PwaInstall } from "@/components/pwa-install";
import { demoAnnouncements } from "@/lib/demo-data";
import { useLocale } from "@/components/locale-provider";
import { formatDate } from "@/lib/utils";
import Link from "next/link";

export default function Dashboard(){const{locale,t}=useLocale();const urgent=demoAnnouncements[0];return <AppShell title={t.dashboardTitle}><PwaInstall/>
 <section className="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="mb-1 text-sm font-semibold text-[var(--primary)]">{t.welcome}</p><h2 className="text-3xl font-black tracking-tight sm:text-4xl">{t.dashboardTitle}</h2><p className="mt-2 text-[var(--muted)]">{locale==="ar"?"قسم":"Department"} <b className="text-[var(--text)]">{t.department}</b></p></div><label className="relative w-full lg:w-[450px]"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-[var(--muted)] rtl:right-4 ltr:left-4 ltr:right-auto" size={19}/><input className="input h-12 rtl:pr-12 ltr:pl-12" placeholder={t.search}/></label></section>
 <div className="mb-6 grid gap-4 sm:grid-cols-3">{[[t.total,"24",FileText,"teal"],[t.unread,"3",Bell,"red"],[t.thisMonth,"8",CalendarDays,"green"]].map(([label,value,Icon,tone])=><article key={String(label)} className="metric-card card"><i className={`metric-icon ${tone}`}><Icon size={25}/></i><div><p className="text-sm text-[var(--muted)]">{label as string}</p><strong className="text-3xl font-black">{value as string}</strong></div></article>)}</div>
 <section className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
  {icon:Building2,title:locale==="ar"?"حول الشركة":"About HAAT",body:locale==="ar"?"نتقرب من الناس كل يوم عبر خدمة توصيل سريعة، موثوقة، وتجربة تضع العميل أولاً.":"We connect people every day through fast, reliable delivery and a customer-first experience.",href:"/community"},
  {icon:ShieldCheck,title:locale==="ar"?"سياسات الشركة":"Company Policies",body:locale==="ar"?"مرجع واضح لسياسات العمل، خدمة العملاء، الأمن، والسلوك المهني.":"A clear reference for workplace, customer service, security, and conduct policies.",href:"/announcements"},
  {icon:Trophy,title:locale==="ar"?"إنجازات الشركة":"Company Achievements",body:locale==="ar"?"نحتفل بإنجازات الفرق والموظفين والنتائج التي نصنعها معاً.":"Celebrating the teams, people, and results we build together.",href:"/community"},
  {icon:CalendarHeart,title:locale==="ar"?"العطل الرسمية":"Official Holidays",body:locale==="ar"?"راجع العطل الرسمية والمناسبات المعتمدة وخطط لجدولك مسبقاً.":"Review approved public holidays and plan your schedule ahead.",href:"/schedule"}
 ].map(({icon:Icon,title,body,href})=><Link key={title} href={href} className="company-section card p-5 transition-transform hover:-translate-y-1"><i className="row-icon mb-4"><Icon size={22}/></i><h3 className="text-lg font-black">{title}</h3><p className="relative z-10 mt-2 text-sm leading-7 text-[var(--muted)]">{body}</p></Link>)}</section>
 <section className="urgent-card card mb-7 p-6 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="badge urgent"><TriangleAlert size={13}/>{t.urgent}</span><span className="badge"><Pin size={13}/>{locale==="ar"?"مثبّت":"Pinned"}</span></div><h3 className="text-xl font-black sm:text-2xl">{locale==="ar"?"تحديث مهم على سياسة خدمة العملاء":"Important customer service policy update"}</h3><p className="mt-3 max-w-3xl leading-8 text-[var(--muted)]">{locale==="ar"?"نود إبلاغكم بتحديثات مهمة على سياسة خدمة العملاء تهدف إلى تحسين تجربة العملاء ورفع جودة الخدمة. يرجى الاطلاع على التفاصيل الكاملة والالتزام بالتحديثات الجديدة.":"Important updates to the customer service policy are now effective. Please review the full details and acknowledge the new procedure."}</p><div className="mt-4 flex flex-wrap items-center gap-4 text-xs text-[var(--muted)]"><span>سارة العتيبي</span><span>{formatDate(urgent.published_at)}</span><span className="flex items-center gap-1"><Paperclip size={14}/>PDF</span></div></div><Link href="/announcements/a1" className="btn btn-primary min-w-44 self-start lg:self-center">{t.read}<span>←</span></Link></div></section>
 <section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">{t.latest}</h2><Link href="/announcements" className="text-sm font-bold text-[var(--primary)]">{t.viewAll}</Link></div><div className="space-y-3">{demoAnnouncements.slice(1,4).map(a=><Link href={`/announcements/${a.id}`} key={a.id} className="announcement-row card"><i className="row-icon">{a.priority==="important"?<TriangleAlert size={21}/>:<CheckCircle2 size={21}/>}</i><div className="min-w-0 flex-1"><h3 className="truncate font-extrabold">{a.title}</h3><p className="mt-1 truncate text-xs text-[var(--muted)]">{a.body}</p></div><span className={`badge ${a.is_read?"read":"unread"}`}>{a.is_read?(locale==="ar"?"مقروءة":"Read"):(locale==="ar"?"غير مقروءة":"Unread")}</span><span className="hidden text-xs text-[var(--muted)] sm:block">{formatDate(a.published_at)}</span></Link>)}</div></section>
 </AppShell>}
