"use client";
import { Ban, Bell, Building2, CalendarHeart, CheckCircle2, ChevronDown, Clock3, Gauge, Headset, RefreshCw, ScanSearch, Search, ShieldCheck, Sparkles, Trophy } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PwaInstall } from "@/components/pwa-install";
import { useLocale } from "@/components/locale-provider";
import { StatCard } from "@/components/ui";
import Link from "next/link";

export default function Dashboard(){const{locale,t}=useLocale();const ar=locale==="ar";const responsibilities=[
 {icon:Headset,title:ar?"استقبال وفهم التوجّه":"Receive and understand",summary:ar?"فهم المشكلة ونوع النقص قبل بدء المتابعة.":"Understand the issue and the missing part before follow-up.",body:ar?"يجب على قسم خدمة الزبائن استقبال توجّه الزبون وفهم المشكلة بوضوح، بما في ذلك ما إذا كان الزبون يستفسر عن جزء ناقص من الطلب أو عن توصيل جزئي.":"Customer Service must clearly understand whether the customer is asking about a missing part of the order or a partial delivery."},
 {icon:ScanSearch,title:ar?"الفحص مع مركز التحكم":"Check with Control Center",summary:ar?"معرفة حالة التوصيل وعدد المرسلين المسؤولين.":"Verify delivery status and whether multiple drivers are involved.",body:ar?"يجب فحص الحالة مع مركز التحكم لفهم حالة التوصيل، وما إذا كان الطلب يتم التعامل معه من قبل أكثر من مرسل.":"Check the case with the Control Center to understand the delivery status and whether the order is being handled by more than one driver."},
 {icon:Ban,title:ar?"عدم اتخاذ إجراء تشغيلي":"No operational action",summary:ar?"يبقى التنفيذ التقني والتشغيلي من مسؤولية الجهة المختصة.":"Technical and operational execution stays with the responsible team.",body:ar?"لا يجوز لقسم خدمة الزبائن اتخاذ أي إجراء تقني أو تشغيلي متعلق بالإسناد، أو التعامل مع المرسلين، أو إجراءات لوحة التحكم.":"Customer Service must not take technical or operational action related to assignment, driver handling, or control-panel procedures."},
 {icon:RefreshCw,title:ar?"التنسيق والتواصل":"Coordinate and communicate",summary:ar?"تحديث الزبون بوضوح وفق آخر معلومة مؤكدة.":"Update the customer clearly using the latest confirmed information.",body:ar?"يقتصر دور قسم خدمة الزبائن على فحص الحالة، والتنسيق مع مركز التحكم، وتحديث الزبون بناءً على المعلومات المستلمة. يجب التواصل معه بوضوح وشرح حالة الطلب وفق التحديث الوارد من مركز التحكم.":"Customer Service checks the case, coordinates with the Control Center, and clearly updates the customer based on the confirmed information received."}
 ];return <AppShell title={t.dashboardTitle}><PwaInstall/>
 <section className="dashboard-hero mb-6"><div className="hero-shape one"/><div className="hero-shape two"/><div className="relative z-10"><span className="hero-kicker"><Sparkles size={14}/>{ar?"مرحباً بعودتك":"Welcome back"}</span><h2>{ar?"صباح الخير، أحمد 👋":"Good morning, Ahmad 👋"}</h2><p>{ar?"هذه نظرة سريعة على يومك وأحدث نشاطات فريقك.":"Here’s a quick look at your day and your team’s latest activity."}</p><div className="hero-meta"><span><Building2 size={15}/>{t.department}</span><span><Clock3 size={15}/>{ar?"الوردية 09:00 – 17:00":"Shift 09:00 – 17:00"}</span></div></div><label className="hero-search"><Search size={19}/><input aria-label={t.search} placeholder={t.search}/></label></section>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label={ar?"درجة الأداء":"Performance score"} value="92%" icon={Gauge} tone="red" trend={5.2} note={ar?"أعلى من متوسط الفريق":"Above team average"}/><StatCard label={ar?"نسبة الحضور":"Attendance rate"} value="97%" icon={CheckCircle2} tone="green" trend={1.4} note={ar?"28 يوم عمل":"28 working days"}/><StatCard label={t.unread} value="3" icon={Bell} tone="orange" trend={-25} note={ar?"تحتاج إلى مراجعتك":"Need your attention"}/><StatCard label={ar?"ترتيب القسم":"Department rank"} value="#3" icon={Trophy} tone="blue" trend={8} note={ar?"من أصل 32 موظف":"Out of 32 employees"}/></div>
 <section className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
  {icon:Building2,title:ar?"حول الشركة":"About HAAT",body:ar?"تعرّف على رؤيتنا، قيمنا، والفرق التي تصنع التجربة.":"Explore our vision, values, and the teams behind the experience.",href:"/community"},
  {icon:ShieldCheck,title:ar?"سياسات الشركة":"Company Policies",body:ar?"مرجع واضح لسياسات العمل وخدمة الزبائن والسلوك المهني.":"A clear reference for workplace, service, and conduct policies.",href:"/announcements"},
  {icon:Trophy,title:ar?"إنجازات الشركة":"Company Achievements",body:ar?"نحتفل بإنجازات الفرق والنتائج التي نصنعها معاً.":"Celebrating the teams and results we build together.",href:"/community"},
  {icon:CalendarHeart,title:ar?"العطل الرسمية":"Official Holidays",body:ar?"راجع العطل الرسمية وخطط لجدولك مسبقاً.":"Review public holidays and plan your schedule ahead.",href:"/schedule"}
 ].map(({icon:Icon,title,body,href})=><Link key={title} href={href} className="company-section card p-5 transition-transform hover:-translate-y-1"><i className="row-icon mb-4"><Icon size={22}/></i><h3 className="text-lg font-black">{title}</h3><p className="relative z-10 mt-2 text-sm leading-7 text-[var(--muted)]">{body}</p></Link>)}</section>
 <details className="work-guide-box mb-7">
  <summary className="work-guide-summary"><i><ShieldCheck size={24}/></i><div><span>{ar?"مرجع الموظف":"Employee reference"}</span><h2>{ar?"دليل العمل - خدمة الزبائن":"Work Guide - Customer Service"}</h2><p>{ar?"مسؤوليات القسم وخطوات التعامل مع الطلبات الكبيرة والتوصيل الجزئي.":"Team responsibilities for large orders and partial deliveries."}</p></div><strong>{ar?"عرض الدليل":"Open guide"}<ChevronDown size={18}/></strong></summary>
  <section className="customer-responsibilities">
   <div className="responsibilities-heading"><div><span><ShieldCheck size={15}/>{ar?"مسؤوليات القسم":"Team responsibilities"}</span><h2>{ar?"مسؤوليات خدمة الزبائن":"Customer Service Responsibilities"}</h2><p>{ar?"عند ورود توجّه متعلق بطلب كبير أو وصول جزء فقط من الطلب، اتبع هذه الخطوات الأربع بالترتيب.":"When a large order arrives partially, follow these four responsibilities in order."}</p></div><strong>4 <small>{ar?"خطوات واضحة":"clear steps"}</small></strong></div>
   <div className="responsibilities-grid">{responsibilities.map(({icon:Icon,title,summary,body},index)=><details key={title} className="responsibility-card" open={index===0}><summary><span className="responsibility-number">{String(index+1).padStart(2,"0")}</span><i><Icon size={21}/></i><div><b>{title}</b><small>{summary}</small></div><ChevronDown className="responsibility-chevron" size={18}/></summary><p>{body}</p></details>)}</div>
   <div className="responsibilities-note"><ShieldCheck size={18}/><p>{ar?"قاعدة أساسية: دور خدمة الزبائن هو الفحص والتنسيق والتحديث الواضح؛ أما الإجراءات التقنية والتشغيلية فتتم من خلال الجهة المختصة.":"Core rule: Customer Service checks, coordinates, and communicates clearly; technical and operational actions belong to the responsible team."}</p></div>
  </section>
 </details>
 </AppShell>}
