"use client";
import { Bell, Building2, CalendarHeart, CheckCircle2, Clock3, Gauge, Paperclip, Pin, Search, ShieldCheck, Sparkles, TriangleAlert, Trophy } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PwaInstall } from "@/components/pwa-install";
import { demoAnnouncements } from "@/lib/demo-data";
import { useLocale } from "@/components/locale-provider";
import { formatDate } from "@/lib/utils";
import { DonutChart, MiniLineChart, StatCard } from "@/components/ui";
import Link from "next/link";

export default function Dashboard(){const{locale,t}=useLocale();const urgent=demoAnnouncements[0];const ar=locale==="ar";return <AppShell title={t.dashboardTitle}><PwaInstall/>
 <section className="dashboard-hero mb-6"><div className="hero-shape one"/><div className="hero-shape two"/><div className="relative z-10"><span className="hero-kicker"><Sparkles size={14}/>{ar?"مرحباً بعودتك":"Welcome back"}</span><h2>{ar?"صباح الخير، أحمد 👋":"Good morning, Ahmad 👋"}</h2><p>{ar?"هذه نظرة سريعة على يومك وأحدث نشاطات فريقك.":"Here’s a quick look at your day and your team’s latest activity."}</p><div className="hero-meta"><span><Building2 size={15}/>{t.department}</span><span><Clock3 size={15}/>{ar?"الوردية 09:00 – 17:00":"Shift 09:00 – 17:00"}</span></div></div><label className="hero-search"><Search size={19}/><input aria-label={t.search} placeholder={t.search}/></label></section>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label={ar?"درجة الأداء":"Performance score"} value="92%" icon={Gauge} tone="red" trend={5.2} note={ar?"أعلى من متوسط الفريق":"Above team average"}/><StatCard label={ar?"نسبة الحضور":"Attendance rate"} value="97%" icon={CheckCircle2} tone="green" trend={1.4} note={ar?"28 يوم عمل":"28 working days"}/><StatCard label={t.unread} value="3" icon={Bell} tone="orange" trend={-25} note={ar?"تحتاج إلى مراجعتك":"Need your attention"}/><StatCard label={ar?"ترتيب القسم":"Department rank"} value="#3" icon={Trophy} tone="blue" trend={8} note={ar?"من أصل 32 موظف":"Out of 32 employees"}/></div>
 <section className="mb-6 grid gap-6 xl:grid-cols-[1.45fr_.55fr]"><article className="chart-card card"><div className="chart-heading"><div><span>{ar?"أداؤك خلال 6 أشهر":"Your 6-month performance"}</span><h3>{ar?"تطور ثابت وملحوظ":"Steady, noticeable growth"}</h3></div><span className="trend-pill">↗ 7.4%</span></div><MiniLineChart values={[72,79,77,85,88,92]} labels={ar?["آذار","نيسان","أيار","حزيران","تموز","آب"]:["Mar","Apr","May","Jun","Jul","Aug"]}/></article><article className="chart-card card flex flex-col items-center justify-center"><DonutChart value={86} label={ar?"مكتمل":"Complete"} caption={ar?"12 من 14 هدفًا شهريًا":"12 of 14 monthly goals"}/></article></section>
 <section className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
  {icon:Building2,title:ar?"حول الشركة":"About HAAT",body:ar?"تعرّف على رؤيتنا، قيمنا، والفرق التي تصنع التجربة.":"Explore our vision, values, and the teams behind the experience.",href:"/community"},
  {icon:ShieldCheck,title:ar?"سياسات الشركة":"Company Policies",body:ar?"مرجع واضح لسياسات العمل وخدمة العملاء والسلوك المهني.":"A clear reference for workplace, service, and conduct policies.",href:"/announcements"},
  {icon:Trophy,title:ar?"إنجازات الشركة":"Company Achievements",body:ar?"نحتفل بإنجازات الفرق والنتائج التي نصنعها معاً.":"Celebrating the teams and results we build together.",href:"/community"},
  {icon:CalendarHeart,title:ar?"العطل الرسمية":"Official Holidays",body:ar?"راجع العطل الرسمية وخطط لجدولك مسبقاً.":"Review public holidays and plan your schedule ahead.",href:"/schedule"}
 ].map(({icon:Icon,title,body,href})=><Link key={title} href={href} className="company-section card p-5 transition-transform hover:-translate-y-1"><i className="row-icon mb-4"><Icon size={22}/></i><h3 className="text-lg font-black">{title}</h3><p className="relative z-10 mt-2 text-sm leading-7 text-[var(--muted)]">{body}</p></Link>)}</section>
 <section className="urgent-card card mb-7 p-6 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="badge urgent"><TriangleAlert size={13}/>{t.urgent}</span><span className="badge"><Pin size={13}/>{ar?"مثبّت":"Pinned"}</span></div><h3 className="text-xl font-black sm:text-2xl">{ar?"تحديث مهم على سياسة خدمة العملاء":"Important customer service policy update"}</h3><p className="mt-3 max-w-3xl leading-8 text-[var(--muted)]">{ar?"تحديثات مهمة تهدف إلى تحسين تجربة العملاء ورفع جودة الخدمة. يرجى الاطلاع على التفاصيل والالتزام بالإجراء الجديد.":"Important updates to the customer service policy are now effective. Please review and acknowledge the new procedure."}</p><div className="mt-4 flex flex-wrap items-center gap-4 text-xs text-[var(--muted)]"><span>سارة العتيبي</span><span>{formatDate(urgent.published_at)}</span><span className="flex items-center gap-1"><Paperclip size={14}/>PDF</span></div></div><Link href="/announcements/a1" className="btn btn-primary min-w-44 self-start lg:self-center">{t.read}<span>←</span></Link></div></section>
 <section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">{t.latest}</h2><Link href="/announcements" className="text-sm font-bold text-[var(--primary)]">{t.viewAll}</Link></div><div className="space-y-3">{demoAnnouncements.slice(1,4).map(a=><Link href={`/announcements/${a.id}`} key={a.id} className="announcement-row card"><i className="row-icon">{a.priority==="important"?<TriangleAlert size={21}/>:<CheckCircle2 size={21}/>}</i><div className="min-w-0 flex-1"><h3 className="truncate font-extrabold">{a.title}</h3><p className="mt-1 truncate text-xs text-[var(--muted)]">{a.body}</p></div><span className={`badge ${a.is_read?"read":"unread"}`}>{a.is_read?(ar?"مقروءة":"Read"):(ar?"غير مقروءة":"Unread")}</span></Link>)}</div></section>
 </AppShell>}
