import { NextRequest, NextResponse } from "next/server";
import { getPortalActor, isManager } from "@/lib/portal-actor";
import { listSimulatorResults, saveSimulatorResult } from "@/lib/knowledge-store";

const scenarios=[
 {id:"late",title:"طلب متأخر والمطعم غير جاهز",customer:"صارلي ساعة ونص بستنى، وإذا ما وصل خلال خمس دقائق بدي ألغي.",required:["اعتذر","تحقق","المطعم","وقت","مشرف"],policy:"إجراء الطلب المتأخر"},
 {id:"missing",title:"طلب ناقص",customer:"وصلني الطلب بس الصنف الرئيسي ناقص، بدي حل الآن.",required:["اعتذر","تحقق","الصنف","وثق","تعويض"],policy:"إجراء الطلب الناقص"},
 {id:"payment",title:"دفعة معلقة",customer:"انخصم المبلغ مرتين وما ظهر الطلب عندي.",required:["تحقق","الدفع","المبلغ","صعد","بيانات"],policy:"سياسة أمن المدفوعات"},
 {id:"restaurant",title:"المطعم لا يجيب",customer:"الطلب متأخر والمطعم ما برد عليكم، شو أعمل؟",required:["تحقق","محاولة","وقت","وثق","مشرف"],policy:"إجراء التواصل مع المطاعم"},
];
export async function GET(request:NextRequest){const history=request.nextUrl.searchParams.get("history")==="1";if(!history)return NextResponse.json({scenarios});try{const actor=await getPortalActor();return NextResponse.json({history:await listSimulatorResults(isManager(actor)&&request.nextUrl.searchParams.get("all")==="1"?undefined:actor.id)})}catch{return NextResponse.json({history:[]})}}
export async function POST(request:Request){const body=await request.json() as{scenarioId?:string;reply?:string;level?:string};const scenario=scenarios.find(s=>s.id===body.scenarioId);if(!scenario||!body.reply?.trim())return NextResponse.json({error:"INVALID_SCENARIO"},{status:422});const text=body.reply.toLowerCase();const hit=scenario.required.filter(word=>text.includes(word)).length;const base=Math.round(45+(hit/scenario.required.length)*50);const scores={communication:Math.min(100,base+5),policyCompliance:base,problemUnderstanding:Math.min(100,base+8),correctProcedure:base,escalationDecision:text.includes("مشرف")||text.includes("صعد")?95:65,compensationDecision:text.includes("تعويض")?80:75,responseQuality:Math.min(100,base+3),professionalism:text.includes("اعتذر")?95:75};const overall=Math.round(Object.values(scores).reduce((a,b)=>a+b,0)/Object.keys(scores).length);const feedback={well:hit>=3?["فهمت المشكلة وحددت خطوات عملية","حافظت على نبرة مهنية"]:["بدأت التعامل مع الحالة"],improve:scenario.required.filter(word=>!text.includes(word)).map(word=>`تضمين خطوة مرتبطة بـ: ${word}`),mistakes:hit<3?["الإجراء غير مكتمل حسب السياسة"]:[],recommended:`أفهم انزعاجك وأعتذر. سأتحقق من الطلب والجهة المعنية، أوثق النتيجة، وأصعّد للمشرف إذا لم يوجد إجراء مؤكد.`,procedure:scenario.required,policy:scenario.policy};try{const actor=await getPortalActor();await saveSimulatorResult({userKey:actor.id,employeeName:actor.fullName,level:body.level||"Beginner",scenarioTitle:scenario.title,overallScore:overall,scores,feedback})}catch{}return NextResponse.json({evaluation:{overall,scores,feedback,policy:scenario.policy}})}
